basePath: /api
definitions:
  models.Filters:
    description: получение людей по фильтрам
    properties:
      age:
        example: 25
        type: integer
      gender:
        example: male
        type: string
      limit:
        type: integer
      name:
        example: Donald
        type: string
      nation:
        example: US
        type: string
      offset:
        type: integer
      patronymic:
        example: Duck
        type: string
      surname:
        example: Trump
        type: string
    required:
    - name
    - surname
    type: object
  models.FullUser:
    description: Полные данные пользователя после обогащения
    properties:
      age:
        example: 25
        type: integer
      gender:
        example: male
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Donald
        type: string
      nation:
        example: US
        type: string
      patronymic:
        example: Duck
        type: string
      surname:
        example: Trump
        type: string
    required:
    - name
    - surname
    type: object
  models.User:
    description: Данные пользователя с дополнительной информацией
    properties:
      age:
        example: 25
        type: integer
      gender:
        example: male
        type: string
      name:
        example: Donald
        type: string
      nation:
        example: US
        type: string
      patronymic:
        example: Duck
        type: string
      surname:
        example: Trump
        type: string
    required:
    - name
    - surname
    type: object
  models.UserInput:
    description: Входные данные для создания пользователя
    properties:
      name:
        example: Donald
        type: string
      patronymic:
        example: Duck
        type: string
      surname:
        example: Trump
        type: string
    required:
    - name
    - surname
    type: object
host: localhost:8080
info:
  contact: {}
  description: Enrichment Service
  title: API Service
  version: 1.0.0
paths:
  /users:
    get:
      consumes:
      - application/json
      description: получение пользователей по фильтру
      parameters:
      - description: Фильтры для получения пользователей
        in: body
        name: filters
        schema:
          $ref: '#/definitions/models.Filters'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: 'error": "Invalid format'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error": "error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение пользователей
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Создание нового пользователя
      parameters:
      - description: User Input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.FullUser'
        "400":
          description: 'error": "Invalid format'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error": "error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание пользователя
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: удаление пользователя по id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'message": "User deleted'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'error": "Invalid format'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error": "error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удаление пользователя
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Изменение данных пользователя по некоторым данным
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User
        in: body
        name: newUserData
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FullUser'
        "400":
          description: 'error": "Invalid format'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error": "error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Изменение данных пользователя
      tags:
      - users
swagger: "2.0"
